sudo: required
dist: trusty

language: java		
jdk: oraclejdk8

install:
  - mkdir /tmp/dynamodb
  - wget -O - http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest | tar xz --directory /tmp/dynamodb

before_script:
  - java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -sharedDb -inMemory -port 35458 &
  - sleep 2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/066a8197f92d460e8530
    on_success: always
    on_failure: always  
    on_start: false  
